name: Docker CI  # Corrected from docker-name to name

# Trigger the workflow on push or pull request to the main branch
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

# Define the jobs to run
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Check out the code from your repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Set up Docker Buildx (required for building multi-platform images)
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      # Step 3: Log in to DockerHub using secrets for credentials
      - name: Log in to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.USERNAME_hub }}  # Ensure this secret is added in GitHub settings
          password: ${{ secrets.PASSWORD_hub }}  # Ensure this secret is added in GitHub settings

      # Step 4: Build the Docker image
      - name: Build Docker Image
        run: docker build -t my-app:latest .

      # Step 5: Run the Docker container
      - name: Run Docker Container
        run: docker run --rm my-app:latest

      # (Optional) Step 6: Push the image to DockerHub
      # Uncomment the following step if you want to push the built image to your DockerHub repository
      # - name: Push Docker Image
      #   run: docker push my-app:latest
